# --- Configurações Principais ---
title: Projeto Tipografar
description: >-
  Portfólio de projetos de estudantes de design tipográfico e lettering desenvolvidos na disciplina Projeto TIpografar nos cursos superiores em Design e Design Gráfico do Centro Universitário Senac - SP.
baseurl: ""
url: ""

# --- Lista de Plugins ---
plugins:
  - jekyll-feed
  - jekyll-archives

# --- Configuração de Build ---
permalink: /projetos/:title/
sass:
  sass_dir: scss
  style: compressed
  load_paths:
    - node_modules

# --- Configuração do Plugin Jekyll Archives ---
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: "list"
    tag: "list"
  permalinks:
    category: "/categorias/:name/"
    tag: "/tags/:name/"
